name: CHECK

on:
  pull_request:
    paths:
    - '**'
  push:
    paths:
    - '**'
    branches:
    - master
  release:
    types: [prereleased, released]

jobs:
  push-workflows-to-airflow:
    name: Push Fusion Workflows to Airflow
    runs-on: ubuntu-latest
    steps:
    - name: Set Dev Env
      if: github.event_name == 'pull_request' || github.event_name == 'push'
      run: echo "ENVIRONMENT=dev"
    - name: Set Preprod Env
      if: github.event_name == 'release' && github.event.release.prerelease
      run: echo "ENVIRONMENT=preprod"
    - name: Set Prod Env (for release)
      if: github.event_name == 'release' && !github.event.release.prerelease
      run: echo "ENVIRONMENT=prod"
    - name: Push to airflow with Actuator
      run: echo "$ENVIRONMENT"
